### ISSUE TITLE
Problem with state status on tile

### ISSUE THREAD

**Issue by dawidfilo** [sgrayban/Hubitat-Ports#1]
**Driver Used**
What driver are you using?
Latest

**Shelly Device**
What device is this for ?
1PM, PlugS

**Describe the bug**
Hello Scott,
I have a small problem with controlling shelly switches via Hubitat dashboard. 
Sometimes when I press the switch on dashboard - shelly is turning on/off properly, but dashboard tile is not changing the state.
So for example: shelly is off, I'm pressing the dashboard switch and shelly is turning on, but dashbord switch still showing OFF state.
Few times switch tile froze on "Sending.." too.
In both cases, to get properly tile state - I must to press it again or wait 1/5/15/30min to refresh.
I think that is happening mostly after hub reboot or when i'm not using those switches for some time, but not 100% sure.

I tried to create some rule to poll device 1 or 2 seconds after switching, but I dont know how.
Condition - poll when switch change its state doesn't work, because.. switch doesn't changing state :)
Only thing thats work for me is virtual button which poll devices when I press it, but this is workaround solution.

I used to try make a rule to poll shellys every few seconds, but it was bad idea. I had hub frozing or rebooting once per day or two.
I even tried did it by Maker API - shelly (via actions) was sending maker api command to poll a device (it was nice in case of turning in on by Shelly App or wall switch) but for long term it doesn't work good either. In this case shellys liked to stop responding, maybe too many commends at once ?

Do you maybe know why is that happening ?

Regards
Dawid

**Comment by sgrayban** [comment]
If you go to the device page and turn it on/off does the switch status change instantly ?

**Comment by dawidfilo** [comment]
Yes, flawless, without any delay.
I wonder if it's not the network issue, or router itself.
Hub and shellys are connected to TP-Link MR400 LTE Router.

**Comment by sgrayban** [comment]
What are the refresh rates for the dashboard ? I set mine at 1 second for local and 3 for internet.

![image](https://user-images.githubusercontent.com/1351910/65940724-11a85480-e3de-11e9-9109-9b50d937ac8b.png)

**Comment by dawidfilo** [comment]
2 sec for LAN and 3 sec for cloud connection.
I'm using Sharptools dashboard too - problem looks the same.

**Comment by sgrayban** [comment]
Must be a networking issue because my local HE dashboard is instant for me. I don't test with sharptools.

**Comment by dawidfilo** [comment]
To be clear - switching on/off and all the stuff works instant for me too. Devices are turning on/off properly, they just have problem with updating status to HE.

**Comment by sgrayban** [comment]
My HE dashboard is instant and the way I wrote the code as soon as a command is sent 2 seconds later the refresh() routine is called.

Can you video what your dashboard is doing ?

**Comment by dawidfilo** [comment]
it works just that way:
- Shelly is OFF
- Clicking on dashboard tile, it shows "sending.." command on bottom of the tile
- Shelly is switching ON instant

And then there are two options:
1. Tile returns to previous (incorrect) OFF state
2. Tile is still showing "sending.."

If I want to "repair" this I must to wait to refresh or press the tile again.
If I press it again - HE is sending ON command again (I see that in logs) and tile is switching to ON then. Shelly does nothing because is already ON.

**Comment by sgrayban** [comment]
And this is when you are using the local dashboard ?

**Comment by dawidfilo** [comment]
Yes, but also with HE cloud dashboard and Sharptools.
I noticed it on all three dashboards.

**Comment by sgrayban** [comment]
It must be a local issue then with your router. I can't reproduce this at all,,, local or not.

**Comment by sgrayban** [comment]
Is it just shelly devices lagging in response or other devices too ?

**Comment by dawidfilo** [comment]
Only shelly, but I haven't got much devices.
Now only 2 shelly's switch connected, 1 H&T (via your MQTT driver), 2 Sonoffs (via IFTTT) and some Zigbee sensors.
I did few virtual switches to just switch them on/off sometimes and check if its maybe HE lag or so, but they work ok.

You know - it's not a big deal, but just annoying.
I think I will try to change a router and will see.

**Comment by sgrayban** [comment]
It has to be your router... something isnt right.

**Comment by dawidfilo** [comment]
[RPReplay_Final1569947747.zip](https://github.com/sgrayban/Hubitat-Ports/files/3677625/RPReplay_Final1569947747.zip)

**Comment by dawidfilo** [comment]
Please take a look, I did a short video which shows that issue.

**Comment by sgrayban** [comment]
I understand what your issue is but I can't reproduce it on my end. My switches turn on/off instantly which leads me to think it's your network somehow.

I have my dashboard refreshing 1 second for local and 3 seconds for internet access and it works.

```groovy
def sendSettingsCommand(action) {
    if (txtEnable) log.info "Setting relay ${channel} ${action}"
    if (username != null) {
        host = "${username}:${password}@${ip}"
    } else {
        host = "${ip}"
    }
    sendHubCommand(new hubitat.device.HubAction(
      method: "POST",
      path: "/settings/relay/" + channel,
      body: action,
      headers: [
        HOST: host,
        "Content-Type": "application/x-www-form-urlencoded"
      ]
    ))
    refresh()
}
```
Last line refreshes the status to reflect the change instantly.

**Comment by dawidfilo** [comment]
I understand your position, and don't blame you at all.
I set refreshing settings to 1 and 3 seconds as you and even disable Sharptools for a while, but without any change.

But I rebooted the hub few times to test and noticed that a problem appears 100% right after reboot. So first click after reboot looks like on the video, second and another are ok.

**Comment by sgrayban** [comment]
So on the actual device page you can click on/off and on the right the switch status changes instantly right ? If that is the case then there is a issue within your network.

> second and another are ok.

So the first time use its slow but after that it's ok ?

**Comment by dawidfilo** [comment]
https://we.tl/t-wQKHOfbGD0

I made another video which I hope answer your questions.
Its starts from rebooting the hub.

As you can see - first "click" doesn't refresh the status.

for the record - problem appears not only after roboot, but in this situation is easy for me to catch and record it.

**Comment by dawidfilo** [comment]
one more thing:
video shows Shelly PlugS, but 1PM works exactly the same - tested it too.
And Hubitat interface is a bit laggy just after reboot, but normally, after few seconds is fast and responsive.

**Comment by sgrayban** [comment]
If the hubitat interface is laggy then it's a app or device causing it and not the shelly.

**Comment by sgrayban** [comment]
I watched that video and I see it does respond exactly the way it's coded. So that means your network is getting slowed down by a bad router or switch.

**Comment by sgrayban** [comment]
https://www.dropbox.com/s/25kg615xip3hcu6/Shelly.mp4?dl=0

**Comment by dawidfilo** [comment]
> If the hubitat interface is laggy then it's a app or device causing it and not the shelly.

I mean - it's laggy on the video, because it is just after reboot and probably checking all devices or whatever.
Just after few seconds working normal, fast.
This is really not important in this case :)

> I watched that video and I see it does respond exactly the way it's coded.

Not understand, sorry.
After first click shelly is switching ON (light lights up next to me), but driver doesn't refresh it and still shows that relay is OFF. So it's showing incorrect status.
and I must to press POLL to get correct status.

I agree that every NEXT switching on/off works 100% correct.

**Comment by dawidfilo** [comment]
> 
> 
> https://www.dropbox.com/s/25kg615xip3hcu6/Shelly.mp4?dl=0

Yes, something like this !
I see it that way:
- Fan is ON
- you are clicking on it
- command is sending (and Fan is probably turning OFF)
- Tile come back to ON state (but Fan is probably OFF then)

**Comment by sgrayban** [comment]
If you are clicking on/off rapidly it's going to just stop working. The command is a URL not a zigbee/zwave command.

On my dashboard it's nearly instant. I don't sit there and just click on/off just to see it lag.

If you are seeing it like I am then it's working as its suppose to. If your dashboard isn't updating within 1-2 seconds then its a network issue.

I don't see how to fix your side with my code. I have others using the same driver and no issues with them. You have to remember this is a URL API and NOT a zigbee/zwave command which is much faster in most cases.
